### ISSUE TITLE
Create Introductory "app", that each idea will be added to. 

### ISSUE THREAD

**Issue by tcg** [lifechurch/youversion-web-open-ideas#1]
Need to create the foundation app that others can easily contribute to. 

See the [README](https://github.com/lifechurch/youversion-web-open-ideas/blob/master/README.md) for a description of what this should "look like".

## TODO list for this issue:

- [ ] Use [create-react-app ](https://github.com/facebook/create-react-app) to create a basic React app. 
- [ ] Add [YouVersion's Melos component library](https://github.com/lifechurch/melos) as a dependency for this project.
- [ ] Create one or two example routes, so others can see a template of how to add a new route to show their component or page. 
- [ ] Create a basic menu / "table of contents" on the home page, of links that navigate to each page/route. 
- [ ] Commit this basic app as the foundational boilerplate that others will contribute their solutions onto.

**Comment by FottyM** [comment]
@tcg should it be with Redux or MobX?

**Comment by michael-martin-al** [comment]
@FottyM it should use `react-router` for creating the routes and `redux` for app state.

**Comment by tcg** [comment]
@FottyM Ah, you're working earlier than I am today. =) But yes, @michael-martin-al's answer is right. I'm sorry I left out those helpful details. =)

**Comment by michael-martin-al** [comment]
Also @FottyM FYI... @adamaverycole put in a PR last night. I'm reviewing it now. Didn't want you guys to get frustrated doing the same thing.

**Comment by adamaverycole** [comment]
@michael-martin-al Everything I threw together is pretty basic. Let me know if I missed anything important.

**Comment by tcg** [comment]
closed by https://github.com/lifechurch/youversion-web-open-ideas/pull/2
