### ISSUE TITLE
Create Routes for Videos Feature

### ISSUE THREAD

**Issue by michael-martin-al** [lifechurch/youversion-web-open-ideas#10]
## Summary
Create empty placeholder components attached to the routes/paths for the videos feature. All new components should pass linting rules defined in `.eslintrc.js`.

## TODO
- [ ] Create `videos` folder in `/src/components`
- [ ] Create `<Videos />` component in new `videos` folder
- [ ] Create `<VideoSeries />` component in new `videos` folder
- [ ] Create `<Video />` component in new `videos` folder
- [ ] Attach `<Videos />` component to path `/videos` in `App.js`
- [ ] Attach `<VideoSeries />` component to path `/videos/:id/series` in `App.js`
- [ ] Attach `<Video />` component to path `/videos/:slug` in `App.js`
