### ISSUE TITLE
Setup Deployment and CI/CD for this Repo

### ISSUE THREAD

**Issue by michael-martin-al** [lifechurch/youversion-web-open-ideas#3]
I don't think this can be completed until #2 is merged.

## Background
The purpose of this repo is to create a sandboxed environment for creating (mostly) React components that will be used on Bible.com and various other YouVersion web applications. So, this site doesn't need to be 💯 rock solid. We just need a fast and easy way for contributors to try out / demo their work on a site. The ultimate goal to create as simple a process as possible.

## Suggested Approach
There are lots of ways we could go with this, but I believe [Netlify](https://www.netlify.com/) would be the easiest to get started. We can always change it later if it doesn't meet our needs.

## TODO

- [ ] Connect this repo with Netlify
- [ ] Configure the best settings for deploying this simple react app with client-side routing
- [ ] Deploy this site to Netlify and add the URL to the README

## Need Help?
I realize that someone may need elevated privileges to this repo in order to make this happen because of the OAuth flow that needs to happen. Just let me know what you need.

**Comment by glasssd** [comment]
@michael-martin-al 
I was able to deploy my fork to Netlify (https://boring-pare-ddcd15.netlify.com/) and Heroku (https://youversion-web-open-ideas.herokuapp.com/). Not sure if that's an option or not. This is way outside of my experience, so I wouldn't claim it has the best settings, but both sites seem to work. If it helps, I can write up the steps I followed for whenever a github admin has time to hook up the repository.

**Comment by michael-martin-al** [comment]
@glasssd thanks for putting some effort into this. After reading your comment, I went into Netlify and connected up our repo. Everything seems to be running fine. We're even able to see preview deploys for pull requests.

**Comment by glasssd** [comment]
@michael-martin-al sorry for the delay. I captured screenshots for each step, but I hadn't figured out how to post them. I was thinking that the instructions might help those contributors that want to deploy their forks and provide a sample URL as part of PR submission.

**Comment by michael-martin-al** [comment]
That's my fault @glasssd. I created an issue that mostly required work by someone with access to this repo. I *think* that Netlify is now automatically deploying a contributors fork when they submit a PR and automatically putting a link into the PR. But, I still think your instructions will be useful for people who aren't ready to submit PRs yet. I'll re-open this issue.

**Comment by glasssd** [comment]
@michael-martin-al, I'm afraid I'm stuck. Do you think we could enable the repository's wiki (settings -> features)? I have the deployment instructions written with a series of screenshots, but I don't see a clean way to serve up the images. I first tried a markdown page with embedded data uri images, but GitHub appears to short-circuit that because of fear of a SVG vulnerability. I next tried an HTML page, but of course that doesn't actually render the HTML. `<duh>` 🥇 Use of the wiki appears to be the preferred venue for this sort of documentation. Thanks!
